#cloud-config
users:
  - name: ${cloudinit_user}
    ssh-authorized-keys:
      - ${ssh_public_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash

ssh_pwauth: false
disable_root: true

packages:
  - wget
  - ntpdate

