#cloud-config
users:
  - name: iac
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - ${ssh_public_key}

write_files:
  - path: /home/iac/hello.txt
    content: |
      Hello World
    owner: iac:iac
    permissions: '0644'