#cloud-config
users:
  - name: ${cloudinit_user}
    ssh-authorized-keys:
      - ssh-ed25519 ${ssh_public_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash

packages:
  - wget
  - ntpdate

ssh_pwauth: false
disable_root: true
