name: Ansible CI

on:
  push:
    branches:
      - main
      - test
      - productie

jobs:
  lint:
    name: Lint & syntax check
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ansible syntax check
        run: |
          ansible-playbook --syntax-check ansible/playbooks/install_web.yml

  deploy:
    name: Run Ansible playbook
    runs-on: self-hosted
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run playbook
        run: |
          ansible-playbook -i inventory.ini ansible/playbooks/install_web.yml
